services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: >
      osrm-routed --algorithm mld /data/czech-republic-latest.osrm

  opentopodata:
    build:
        context: ./opentopodata
        dockerfile: docker/Dockerfile 
    container_name: opentopodata
    ports:
      - "5001:5000"
    volumes:
      - ./opentopodata/data:/app/data
